package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Condition.visible;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;
import  static cloud.autotests.helpers.Autorisation.auth;

@Tag("simple")
public class DoramaLiveTests extends TestBase {

    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("личный кабинет")
    void registrationTest() {
      auth(login,password);
        step("проверяем что появилось имя личного кабинета", () -> {
            $(".dropdown-toggle").shouldBe(visible);
        });
    }


    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("меню сайта")
    void menuTest() {
        step("// меню сайта", () -> {
            open("https://doramalive.ru/");
            $(".dropdown-toggle").click();
            $$(".root-item").findBy(text("форум")).click();
            $$(".root-item").findBy(text("справка")).click();
            $$(".root-item").findBy(text("помочь сайту")).click();
            $(".fa.fa-child").click();
        });
        step("проверяем что в меню есть названия клавиш", () -> {
            $(".navbar-collapse.collapse").shouldHave(text("форум"), text("справка"), text("помочь сайту"));
        });
    }


    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("поиск фильма")
    void generatedTest() {
        auth(login,password);

        step("поиск и добавления фильма в отложеные", () -> {
            $("#title-search").click();
            $("#searchLive").setValue("мы все мертвы").pressEnter();
            $("#bookmark-533616").click();
            $$("#modal-bmark").findBy(text("отложено")).click();
        });
        step("проверяем что название фильма совпадает с поиском", () -> {
            $(".media-body").shouldHave(text("мы все мертвы"));
        });
    }


    @Test
    @Description("Autogenerated test")
    @DisplayName("заголовок страницы должен содержать текст заголовка")
    void titleTest() {
        step("Open url 'https://doramalive.ru/'", () ->
            open("https://doramalive.ru/"));

        step("заголовок страницы должен содержать текст заголовка 'Дорамы смотреть онлайн на Dorama live'", () -> {
            String expectedTitle = "Дорамы смотреть онлайн на Dorama live";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }


    @Test
    @Description("Autogenerated test")
    @DisplayName("журнал консоли страницы не должен содержать ошибок")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://doramalive.ru/'", () ->
            open("https://doramalive.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}